language: java

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "sgoutouly-github"

script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar